version: "3.8"

services:
  lighttpd:
    image: jojomi/lighttpd-static
    volumes:
      - $PWD/www:/var/www
      - $PWD/configs/hivemq_config.js:/var/www/hivemq-mqtt-web-client/config.js
      - $PWD/configs/simple_mqtt_config.js:/var/www/simple-mqtt-websocket-example/config.js
    ports:
      - "8080:80"
    links:
      - mosquitto
    networks:
      - mqtt-net

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

    networks:
      - mqtt-net
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf    
    
  nodered:
    image: nodered/node-red
    links:
      - mosquitto
    ports:
      - "1880:1880"
    networks:
      - mqtt-net      

    
  nginx:
    build: ./nginx      
    restart: always
    ports: 
      - 80:80
    networks:
      - mqtt-net  
     
      
      
      
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - mqtt-net
    volumes:
      - influxdb-data:/var/lib/influxdb
  
  telegraf:
    image: telegraf:latest
    environment:
      - TZ=Europe/Moscow
    restart: always
    volumes:
      - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - mqtt-net
  
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mqtt-net
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb


volumes:
    influxdb-data:
    grafana-data:    
  

networks:
  mqtt-net:
  telegraf-net:
  influx-net:
  grafana-net:
