version: "3.8"

services:
  

  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

    networks:
      - mqtt-net
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf    
      - ./mosquitto/config/passwd_file:/etc/mosquitto/passwd_file   
    

    
  nginx:
    build: ./nginx      
    restart: always
    ports: 
      - 80:80
      - 443:443
    networks:
      - mqtt-net  
    volumes:
      - ./data/certs/server.crt:/etc/ssl/certs/server.crt
      - ./data/certs/server.key:/etc/ssl/private/server.key
     
      
      
      
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - mqtt-net
    volumes:
      - influxdb-data:/var/lib/influxdb
  
  telegraf:
    image: telegraf:latest
    environment:
      - TZ=Europe/Moscow
    restart: always
    volumes:
      - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mqtt
      - influxdb
    networks:
      - mqtt-net
  
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mqtt-net
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb


volumes:
    influxdb-data:
    grafana-data:    
  

networks:
  mqtt-net:
  telegraf-net:
  influx-net:
  grafana-net:
