version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

    networks:
      - mqtt-net
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf    
  
  nginx:
    build: ./nginx      
    restart: always
    ports: 
      - 80:80
    networks:
      - mqtt-net  
     
      
      
      
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - mqtt-net
    volumes:
      - influxdb-data:/var/lib/influxdb
  
  telegraf:
    image: telegraf:latest
    environment:
      - TZ=Europe/Moscow
    restart: always
    volumes:
      - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - mqtt-net
  
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mqtt-net
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini        
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb


volumes:
    influxdb-data:
    grafana-data:    
  

networks:
  mqtt-net:
  telegraf-net:
  influx-net:
  grafana-net:
